name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    ## Docker Hub Login and Push ##
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Frontend Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }} .

    - name: Push the Frontend Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}

    - name: Tag the Frontend Docker image as latest and push to Docker Hub
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    ## GitHub Container Registry (GHCR) Login and Push ##
    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag the Frontend Docker image for GHCR and push
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/frontend:${{ github.sha }}

    - name: Tag the Frontend Docker image as latest for GHCR and push
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/frontend:latest
        docker push ghcr.io/${{ github.repository_owner }}/frontend:latest
